print("Сейчас будут решены следующие функции:")
print("1) x=n^b+b^2")
print("2) a=sin(x^2+b^2)")
print("3) y=ln a/lg b^3")
print()
print("Первый аргумент n=8.1")
n=float(8.1)
b=float(input("Введите второй аргумент b: "))
import math
x=math.pow(n,b)+math.pow(b,2)
print("Результат первго примера, x=","%.2f" % (x))
a=math.sin(math.pow(x,2)+math.pow(b,2))
print("Результат второго примера, a=","%.2f" % (a))
y=math.log(a)/math.log(math.pow(b,3))
print("Результат третьего примера, y=","%.2f" % (y))